Stud_project/urls.py
from django.contrib import admin
from django.urls import path
from stud_app import views,view_2,view_3

urlpatterns = [
    path('admin/', admin.site.urls),
    path('welcome/',views.welcome,name="welcome_page"),
    path('student/',views.StudentView.as_view(),name="student-list"),
    path('student/create/',views.StudentCreate.as_view(),name="student-create"),
    path("student/update/<int:pk>", views.StudentUpdate.as_view(), name="student-update"),
    path("student/delete/<int:pk>", views.StudentDelete.as_view(), name="student-delete"),
    path("student/details/<int:pk>", views.StudentDetailView.as_view(), name="student-detail-view"),

    # View_2 Started here

    path("v2/student/", view_2.StudentDetails.as_view(), name="v2-get-student"),

    # view_3 started here
    path("v3/student/", view_3.student_details, name="v3-get-student")



]

stud_app/models.py
from django.db import models

# Create your models here.

class Student_Data(models.Model):
    name = models.CharField(max_length=250)
    roll_no = models.IntegerField()

stud_app/views.py
from django.shortcuts import render,HttpResponse
from django.urls import reverse_lazy


from django.views.generic import ListView, CreateView, UpdateView, DeleteView,DetailView
from stud_app.models import Student_Data
# Create your views here.


class StudentView(ListView):
    model = Student_Data


class StudentDetailView(DetailView):
    model = Student_Data
    queryset = Student_Data.objects.all()


# application_name/Student_data_list.html
# object_list



    # def get_queryset(self):
    #
    #     return Student_Data.objects.filter(name="SATISH SONAWALE").all()




class StudentCreate(CreateView):
    model = Student_Data

    fields = ['name','roll_no']
    success_url = reverse_lazy("satish")


class StudentUpdate(UpdateView):
    model = Student_Data

    fields = ['name','roll_no']

    success_url = reverse_lazy("student-list")


class StudentDelete(DeleteView):
    model = Student_Data
    success_url = reverse_lazy("student-list")




def welcome(request):

    return HttpResponse("Hello")

stud_app/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello title</title>
</head>
<body>

</body>
</html>

stud_app/templates/stud_app/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello title</title>
</head>
<body>
{% for student in student_data_list %}
{{ student.id }}
{{student.name}}
{{student.roll_no}}<br>
{% endfor %}

</body>
</html>

stud_app/templates/stud_app/student_data_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{{object.name}}
{{object.roll_no}}

</body>
</html>

stud_app/templates/stud_app/student_data_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>hfhvbfkbvfkv</title>
</head>
<body>

</body>
</html>

stud_app/templates/stud_app/student_data_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student Data</title>
</head>
<body>
{% for student in student_data_list %}
{{ student.id }}
{{student.name}}
{{student.roll_no}}<br>
{% endfor %}

</body>
</html>